import std/[tables]
import pkg/[vmath, bumpy, chroma]
import ./[events, properties, uiobj, uiobjMacros, window, rendering]

export vmath, bumpy, chroma, tables
export events, properties, rendering, uiobj, uiobjMacros, window


type
  # todo: merge UiRect and UiRectBorder into a single Box with fill/stroke
  # todo: move dashing settings of UiRectBorder into separate object

  UiRect* = ref object of Uiobj
    ## single-color rectangle

    color*: Property[Col] = color(0, 0, 0).property
      ## fill color of this rect
    radius*: Property[float32]
      ## rounding radius foa all four courners
      ## todo: use SideOffsets-like object for radius?
  

  UiImage* = ref object of Uiobj
    ## raster image

    radius*: Property[float32]
      ## rounding radius foa all four courners
    blend*: Property[bool] = true.property
      ## if false, image will be drawn without color mixin with current background
    imageWh*: Property[IVec2]
      ## size of source image in pixels
    color*: Property[Col] = color(1, 1, 1).property
      ## color to multiply with each pixel of image, or color of every non-transparent pixel of the image if colorOverlay is true
    colorOverlay*: Property[bool]
      ## if true, image will have flat color, with image alpha working like a mask (useful for icons)
    
    tex: DrawContextImage
      ## the image loaded to GPU


  SvgImage* {.deprecated: "use UiSvgImage instead".} = UiSvgImage
  UiSvgImage* = ref object of Uiobj
    ## pixel-perfect svg image
    ## expensive resize

    radius*: Property[float32]
      ## rounding radius foa all four courners
    blend*: Property[bool] = true.property
      ## if false, image will be drawn without color mixin with current background
    image*: Property[string]
      ## source svg image text
    imageWh*: Property[IVec2]
      ## size of source image in pixels (if specified in svg file)
    color*: Property[Col] = color(0, 0, 0).property
      ## color of every non-transparent pixel of the image
    
    tex: DrawContextImage


  RectBorder* {.deprecated: "use UiRectBorder instead".} = UiRectBorder
  UiRectBorder* = ref object of UiRect
    ## thin rectangular line, representing a border

    borderWidth*: Property[float32] = 1'f32.property
      ## width of the border line, extends inside component's rect
    dashingPattern*: Property[array[2, float32]] = [1'f32, 0].property
      ## [length in pixels of the visible part, length in pixels of the gap]

  UiRectStroke* {.deprecated: "renamed to UiRectBorder".} = UiRectBorder
  RectStroke* {.deprecated: "renamed to UiRectBorder".} = UiRectBorder


  UiRectShadow* {.deprecated: "use RectShadow instead".} = RectShadow
  RectShadow* = ref object of UiRect
    ## shadow of a rect

    blurRadius*: Property[float32]
      ## length of the gradient between (transparent) side and (flat-colored) inside
      ## todo: make blur outside of component's rect, this is the most used case, setting margin equal to negative blurRadius is inconvinient
  

  UiClipRect* {.deprecated: "use ClipRect instead".} = ClipRect
  ClipRect* = ref object of Uiobj
    ## displays content clipping it to the box of this component

    radius*: Property[float32]
      ## rounding radius for all four courners
    color*: Property[Col] = color(1, 1, 1).property
      ## color to multiply with each pixel of the content of this component
  

  UiText* = ref object of Uiobj
    text*: Property[string]
      ## the text to display
    font*: Property[FontFace]
      ## font (typeface and fontSize) of text to display. Must be provided or text won't display
    bounds*: Property[Vec2]
      ## bounds of arrangement generated by pixie, can be used to display multiline text. If zero, text is displayed in single line
    hAlign*: Property[HorizontalAlignment]
      ## horizontal alignment of arrangement generated by pixie, used in multiline text
    vAlign*: Property[VerticalAlignment]
      ## vertical alignment of arrangement generated by pixie, used in multiline text
    color*: Property[Col] = color(0, 0, 0).property
      ## color of the text

    arrangement*: Property[TextArrangement]
      ## arrangement, generated by pixie (automatically, if text and font are set)


registerComponent UiRect
registerComponent UiImage
registerComponent UiSvgImage
registerComponent UiRectBorder
registerComponent RectShadow
registerComponent ClipRect
registerComponent UiText



#----- Basic Components -----

proc `image=`*(obj: UiImage, img: DrawContextImage) =
  obj.tex = img
  if obj.tex != nil:
    if obj.wh == vec2():
      obj.wh = obj.tex.size.vec2
    obj.imageWh[] = obj.tex.size

method drawInner*(this: UiRect, ctx: DrawContext) =
  ctx.fillRect(
    this.xy.posToGlobal(this.parent), this.wh,
    this.color[], this.radius, this.color[].a != 1 or this.radius != 0
  )


method drawInner*(this: UiImage, ctx: DrawContext) =
  if this.tex == nil: return
  if this.colorOverlay[]:
    ctx.drawIcon(
      this.xy.posToGlobal(this.parent), this.wh, this.tex,
      this.color, this.radius, this.blend or this.radius != 0
    )
  else:
    ctx.drawImage(
      this.xy.posToGlobal(this.parent), this.wh, this.tex,
      this.color, this.radius, this.blend or this.radius != 0
    )


method init*(this: UiSvgImage) =
  procCall this.super.init

  var prevSize = ivec2(0, 0)
  proc updateTexture(size = ivec2()) =
    let sz =
      if size.x > 0 and size.y > 0: size
      elif this.w[].int32 > 0 and this.h[].int32 > 0: this.wh.ivec2
      else: ivec2(0, 0)
    
    prevSize = size
    
    if this.image{} != "":
      this.tex = this.root.ctx.parseSvg(sz, this.image[])
      this.imageWh[] = this.tex.size
      this.wh = this.tex.size.vec2

  this.image.changed.connectTo this: updateTexture()
  this.w.changed.connectTo this: updateTexture(this.wh.ceil.ivec2)
  this.h.changed.connectTo this: updateTexture(this.wh.ceil.ivec2)


method drawInner*(ico: UiSvgImage, ctx: DrawContext) =
  if ico.tex == nil: return
  ctx.drawIcon(
    ico.xy.posToGlobal(ico.parent), ico.wh.ceil,
    ico.tex, ico.color{},
    ico.radius{}, ico.blend{} or ico.radius{} != 0,
  )


proc `fontSize=`*(this: UiText, size: float32) =
  this.font{}.size = size
  this.font.changed.emit()

method init*(this: UiText) =
  procCall this.super.init

  this.arrangement.changed.connectTo this:
    if this.arrangement{} != nil:
      this.wh = this.arrangement{}.size
    else:
      this.wh = vec2()

  proc newArrangement(this: UiText): TextArrangement =
    if this.text{} != "" and this.font{} != nil:
      this.root.ctx.textArrangement(this.font{}, this.text{}, this.bounds{}, this.hAlign{}, this.vAlign{})
    else: nil

  this.text.changed.connectTo this: this.arrangement[] = newArrangement(this)
  this.font.changed.connectTo this: this.arrangement[] = newArrangement(this)
  this.bounds.changed.connectTo this: this.arrangement[] = newArrangement(this)
  this.hAlign.changed.connectTo this: this.arrangement[] = newArrangement(this)
  this.vAlign.changed.connectTo this: this.arrangement[] = newArrangement(this)


method drawInner*(text: UiText, ctx: DrawContext) =
  ctx.drawRasterText(
    text.xy.posToGlobal(text.parent), text.arrangement{}, text.color{}
  )


method drawInner*(rect: UiRectBorder, ctx: DrawContext) =
  ctx.drawRect(
    rect.xy.posToGlobal(rect.parent), rect.wh, rect.color{},
    thickness = rect.borderWidth{}, radius = rect.radius{}, blend = true,
    dashingPattern = rect.dashingPattern{},
  )


method drawInner*(rect: RectShadow, ctx: DrawContext) =
  ctx.drawShadowRect(
    rect.xy.posToGlobal(rect.parent), rect.wh,
    rect.color{},
    rect.blurRadius{},
    radius = rect.radius{},
  )


method draw*(this: ClipRect, ctx: DrawContext) =
  # todo: sometimes draws nothing if ClipRect was created without parent and added to a parent later (which should be an error, though)
  this.drawBefore(ctx)
  if this.visibility == visible:
    if this.w[] <= 0 or this.h[] <= 0: return
    ctx.pushClipRect(this.xy.posToGlobal(this.parent), this.wh, this.radius[])
    try:
      this.drawBeforeChilds(ctx)
      this.drawChilds(ctx)
    finally:
      ctx.popClipRect()
  else:
    this.drawBeforeChilds(ctx)
    this.drawChilds(ctx)
  this.drawAfterLayer(ctx)

